# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               OdinsPlasmaRifle
tagline:             'Stuff and nonsense'
description:         'A wild coder appears!'
url:                 http://odinsplasmarifle.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joshua van Besouw
  github:            https://github.com/OdinsPlasmaRifle
  url:               http://odinsplasmarifle.github.io
  email:

# Custom vars
version:             1.0.0
