# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               OdinsPlasmaRifle
tagline:             'Random stuff'
description:         'The personal blog of Joshua van Besouw'
url:                 http://odinsplasmarifle.github.io
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Joshua van Besouw
  github:            https://github.com/OdinsPlasmaRifle
  url:               http://odinsplasmarifle.github.io
  email:

# Custom vars
version:             1.0.0
